[character]
success_symbol = "[](#908caa)"
error_symbol = "[](#eb6f92)"
vicmd_symbol = "[](green)"

[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

#[git_status]
#disabled = true
